export const allActions = {

    AUTH_KEY: 'AUTH_KEY',
    GET_USERS_REQUESTED: 'GET_USERS_REQUESTED',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILED: 'GET_USERS_FAILED',
    LOG_OUT:'LOG_OUT',
    CURRENT_SCREEN:'CURRENT_SCREEN',
    TRANSFERED_REQ:'TRANSFERED_REQ',
    ACCEPTED_CHATS:'ACCEPTED_CHATS',
    SOCKET:'SOCKET',
    CONTACTS_GET_DATA_REQUEST:'CONTACTS_GET_DATA_REQUEST',
    CONTACTS_SUCCESS_DATA_REQUEST:'CONTACTS_SUCCESS_DATA_REQUEST',
    ARCHIVE_GET_DATA_REQUEST:'ARCHIVE_GET_DATA_REQUEST',
    ARCHIVE_SUCCESS_DATA_REQUEST:'ARCHIVE_SUCCESS_DATA_REQUEST',
    VISITOR_GET_DATA_REQUEST:'VISITOR_GET_DATA_REQUEST',
    VISITOR_SUCCESS_DATA_REQUEST:'VISITOR_SUCCESS_DATA_REQUEST',
    



};

